const express=require("express")
const mongoose=require("mongoose")
const employees=require("./employees/routes/getEmployees.route")
const students=require("./students/routes/Students.route")
const assignments=require("./employees/routes/EmployeeAssignments.route")
const fees=require("./students/routes/studentfee.route")
const result=require("./students/routes/studentResult.route")
const login=require("./login")
const register=require("./Users/routes/user.route")
const app=express()
const cors=require("cors")
require("dotenv").config()
mongoose.connect("mongodb://localhost:27017/Assignments").then(console.log('connected to db'))
app.use(express.json())
app.use(cors())
app.use("/api",employees)
app.use("/api",assignments)
app.use("/api",students)
app.use("/api",fees)
app.use("/api",result)
app.use("/api",login)
app.use("/api",register)
const port=process.env.PORT ||4000
app.listen(port,()=>console.log(`api is listening on port ${port}`))